### ISSUE TITLE
No more messages in websocket since update to v1.3.10

### ISSUE THREAD

**Issue by anthonyst91** [foosel/OctoPrint#2946]
Hello Gina,

Since the update from v1.3.09 to v1.3.10, there are no more messages in the websocket.

Steps to reproduce:
- open websocket "ws://192.168.1.30/sockjs/websocket" using a simple web socket client
- wait a few seconds: connection is established
- only message {"connected": {"display_version": "1.3.10", "apikey": "18B6761E426549FB89C7CD6B9E7D33CB", "branch": "HEAD -> master", "plugin_hash": "3c9f178fb30bec4b9b0461942f398d8a", "config_hash": "bcf6b1c5543b308f316e3c02bb81d915", "version": "1.3.10", "safe_mode": false, "debug": false}} is showing
- there are no more messages after this one

May something has changed in OctoPrint v1.3.10 about the web socket? 

**What were you doing?**
Opening websocket in Printoid to listen for terminal & plugin messages, after updating from v1.3.09 to v1.3.10

**What did you expect to happen?**
See all the messages in the feed (such as plugins messages, terminal messages...)

**What happened instead?**
No messages are showing at all.

**Version of OctoPrint**
OctoPrint 1.3.10

**Operating System running OctoPrint**
Raspbian Stretch on Raspberry Pi 3B (OctoPi 0.15.1)

**Browser and version of browser, operating system running browser**
It does not import for this issue

**Link to octoprint.log**
[File uploaded here](http://s000.tinyupload.com/index.php?file_id=65281255367499922050)

Here is an interesting part of the logs:
2018-12-10 17:45:27,240 - octoprint.server.util.sockjs - INFO - Client connection closed: ::ffff:92.184.117.98
2018-12-10 17:45:27,244 - octoprint.server.util.sockjs - WARNING - Could not send message to client ::ffff:92.184.117.98: 'NoneType' object has no attribute 'send_pack'
2018-12-10 17:45:27,246 - octoprint.server.util.sockjs - WARNING - Could not send message to client ::ffff:92.184.117.98: 'NoneType' object has no attribute 'send_pack'
2018-12-10 17:45:27,252 - octoprint.server.util.sockjs - WARNING - Could not send message to client ::ffff:92.184.117.98: 'NoneType' object has no attribute 'send_pack'
2018-12-10 17:45:27,255 - octoprint.server.util.sockjs - WARNING - Could not send message to client ::ffff:92.184.117.98: 'NoneType' object has no attribute 'send_pack'
2018-12-10 17:45:27,257 - octoprint.server.util.sockjs - WARNING - Could not send message to client ::ffff:92.184.117.98: 'NoneType' object has no attribute 'send_pack'
2018-12-10 17:45:27,259 - octoprint.server.util.sockjs - WARNING - Could not send message to client ::ffff:92.184.117.98: 'NoneType' object has no attribute 'send_pack'
2018-12-10 17:45:27,262 - octoprint.server.util.sockjs - WARNING - Could not send message to client ::ffff:92.184.117.98: 'NoneType' object has no attribute 'send_pack'
2018-12-10 17:45:27,264 - octoprint.server.util.sockjs - WARNING - Could not send message to client ::ffff:92.184.117.98: 'NoneType' object has no attribute 'send_pack'
2018-12-10 17:45:27,267 - octoprint.server.util.sockjs - WARNING - Could not send message to client ::ffff:92.184.117.98: 'NoneType' object has no attribute 'send_pack'
2018-12-10 17:45:27,269 - octoprint.server.util.sockjs - WARNING - Could not send message to client ::ffff:92.184.117.98: 'NoneType' object has no attribute 'send_pack'
2018-12-10 17:45:27,274 - octoprint.server.util.sockjs - WARNING - Could not send message to client ::ffff:92.184.117.98: 'NoneType' object has no attribute 'send_pack'
2018-12-10 17:45:27,278 - octoprint.server.util.sockjs - WARNING - Could not send message to client ::ffff:92.184.117.98: 'NoneType' object has no attribute 'send_pack'
[...]

**Link to contents of terminal tab or serial.log**

**Link to contents of Javascript console in the browser**

**Comment by GitIssueBot** [comment]
Hi @anthonyst91,

It looks like there is some **information missing** from your bug report that will be needed in order to solve the problem. Read the [Contribution Guidelines](https://github.com/foosel/OctoPrint/blob/master/CONTRIBUTING.md) which will provide you with a template to fill out here so that your bug report is ready to be investigated (I promise I'll go away then too!).

If you did not intend to report a bug but wanted to **request a feature or brain storm** about some kind of development, please take special note of the title format to use as described in the [Contribution Guidelines](https://github.com/foosel/OctoPrint/blob/master/CONTRIBUTING.md).

**Please do not abuse the bug tracker as a support forum** - that can be found at [discourse.octoprint.org](https://discourse.octoprint.org). Go there for any kind of issues with network connectivity, webcam functionality, printer detection or any other kind of such support requests or general questions.

Also **make sure you are at the right place** - this is the bug tracker of the official version of OctoPrint, not the Raspberry Pi image OctoPi nor any unbundled third party OctoPrint plugins or unofficial versions. Make sure too that you have **read through the [Frequently Asked Questions](http://faq.octoprint.org)** and searched the [**existing tickets**](https://github.com/foosel/OctoPrint/search?q=&ref=cmdform&type=Issues) for your problem - try multiple search terms please.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next two weeks (until 2018-12-24 19:00 UTC) I'll close this ticket so it doesn't clutter the bug tracker. This is nothing personal, so please just be considerate and help the maintainers solve this problem quickly by following the guidelines linked above. Remember, the less time the devs have to spend running after information on tickets, the more time they have to actually solve problems and add awesome new features. Thank you!

Best regards,
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being, so don't expect any replies from me :) Your ticket is read by humans too, I'm just not one of them.

**Comment by jubaleth** [comment]
Hi @anthonyst91,

There is nothing that needs correcting on the OctoPrint side. You need to send an auth message in the socket... This has been documented (http://docs.octoprint.org/en/maintenance/api/push.html  -- note: the master branch of the docs doesn't seem to be updated, that will be looked into tomorrow) and a notification sent out to third party devs (who opted in) warning of this. I'll point out that there have been 4 RCs released over the last month, this is really something you should have already seen in preparation for the stable release.

**Comment by anthonyst91** [comment]
Hi @jubaleth,

Thanks for your quick feedback. Indeed I did not get the info. My bad, I had to register to these emails before...

Unfortunately I had to test my app with the latest 1.3.10 RC and did not noticed this "issue". Everything was still working fine, even on fresh installs. Today I've re-installed a Raspberry Pi with a fresh install of Raspbian + the lastest 1.3.10 stable, and the behavior starts to occur. I don't understand why...

Moreover, after updating to v1.3.10 stable, some of my users noticed that the websocket was still working fine (whereas I did not updated the app to login & send the auth message over the socket). That's strange too!
